[package]
name = "fencryption"
authors = ["valflrt"]
version = "0.1.4"
edition = "2021"

[dependencies]
aes-gcm = "0.10.1"
base64 = "0.13.0"
clap = { version = "3.2.17", features = ["derive"] }
rand = "0.8.5"
ring = "0.16.20"
