[package]
name = "fencryption"
authors = ["valflrt"]
version = "0.1.6"
edition = "2021"

[dependencies]
aes-gcm = "0.10.1"
clap = { version = "4.0.18", features = ["derive"] }
human-duration = "0.1.0"
rand = "0.8.5"
ring = "0.16.20"
threadpool = "1.8.1"
uuid = { version = "1.2.1", features = ["v4"] }
