name: build

on:
  push:
    paths-ignore:
      - "docs/*"
      - "scripts/*"
      - "README.md"
      - "LICENSE"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: npm run build
