name: release

on:
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  release:
    name: Release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: fencryption
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
