name: release

on:
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/tests.yml
  release:
    name: Release
    needs: test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: fencryption
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
