name: release

on:
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/tests.yml
  release:
    name: Release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        bin_path:
          - "target/release/fencryption"
          - "target/release/fencryption.exe"
          - "target/release/fencryption"
        bin_name:
          - "fencryption-ubuntu"
          - "fencryption-windows.exe"
          - "fencryption-macOS"
    runs-on: ${{ matrix.os }}
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build
        run: cargo build -r
      - name: Rename binaries
        run: cp ${{ matrix.bin_path }} bin/${{ matrix.bin_path }}
      - name: Upload binaries
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: bin/${{ matrix.bin_path }}
