name: release

on:
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Compile
        run: cargo check
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    needs: [compile]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Test
        run: cargo test
  release:
    name: Release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        bin_path:
          - "target/release/fencryption"
          - "target/release/fencryption.exe"
          - "target/release/fencryption"
    runs-on: ${{ matrix.os }}
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build
        run: cargo build -r
      - name: Upload binaries
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: ${{ matrix.bin_path }}
