name: tests

on:
  push:
    paths-ignore:
      - "docs/*"
      - "scripts/*"
      - "README.md"
      - "LICENSE"
    tags-ignore:
      - "*"
  workflow_dispatch:
  workflow_call:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Compile
        run: cargo check
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Test
        run: cargo test -- --test-threads 1
