name: tests

on:
  push:
    paths-ignore:
      - "docs/*"
      - "scripts/*"
      - "README.md"
      - "LICENSE"
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Compile
        run: cargo check
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        rust:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    needs: [compile]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Test
        run: cargo test
